service: python-ansible-layers
frameworkVersion: ">=1.34.0 <2.0.0"

provider:
  name: aws

layers:
  ansiblePython36:
    path: layer
    description: A Layer for running ansible in Python 3.6 Lambda functions
    compatibleRuntimes:
      - python3.6
